name: Deploy Dashboard Producción

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest changes
        run: |
          cd /var/www/html/insp_pry/dashboard
          git fetch origin main
          git reset --hard origin/main
